name: Graphic02
favicon: null
layout_spectrum: 0.05822071270085871
typography_spectrum: 0.8020411664620042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5555633497424424
  lightness: 0.9212709623388946
  saturation: 0.4238212308846414
  rhythmicContrast: 0.5893732921686023
purpose: []
